# Artifactory Settings
artifactory_url          = "http://localhost:8082"
artifactory_access_token = "eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJIYmJBUTQybjFzR2ZXWmdXLUwwXzF2WmVxbXZzcmVEVXM4TmlzMU1PNy1vIn0.eyJleHQiOiJ7XCJyZXZvY2FibGVcIjpcInRydWVcIn0iLCJzdWIiOiJqZmFjQDAxZ2IzYXRrcG54dHFrMGg0eGg5bm0wNnkwXC91c2Vyc1wvdGZfdGVzdCIsInNjcCI6ImFwcGxpZWQtcGVybWlzc2lvbnNcL2FkbWluIiwiYXVkIjoiKkAqIiwiaXNzIjoiamZmZUAwMDAiLCJleHAiOjE2OTI3MjY4NjIsImlhdCI6MTY2MTE5MDg2MiwianRpIjoiYjgzYTg2OTgtMmZkYS00MmJmLWI4OTktNTk0NjY3NTdmOTFlIn0.M1cqANOvluxbdxE946eE9BGo1nkr8xRpwGGMyBUILY0fMBLlF7cgZ0TE_gZ6Jr-byFuFATML5aBNSm1Aro6foNL2IBAdMDP_JL5ya4AUePrGXsk7zZjo-SWqOY0oL9dFjy79BCmi978_LFdZBXpN29GDZMxl0h-xqWVI9gQOm84PUPgdkRE4pcXDPdEmg3WBEqgqyTXRs9uX_LmzzTxoycVGmtjUhZPc0CsZqQ6xd7U3BsD9uT4FNHgD_C4D_hIXVHvStBCGIBZ8hx2unYrFwdOgnsfyzHe57gR_Yl-R6RnEBxaW8zR8podlgK4cCa4JVTtvkuLDo-SkGyStPzs4Xw"


# Ivy Local Settings
ivy_repo_name = "tf-test"

# Maven Remote settings
mvn_repo_name  = "tf-test-mvn"
mvn_remote_url = "https://repo1.maven.org/maven2/"
